#spring:
#  datasource:
#    url: jdbc:h2:./SpringReact
#    username: SA
#  jpa:
#    hibernate:
#      ddl-auto: update
spring:
    jpa:
        properties:
          javax:
            persistence:
              validation:
                mode: none
